DELETE FROM public.question_keys_private;
DELETE FROM public.questions_public;
ALTER SEQUENCE public.questions_public_id_seq RESTART WITH 1;
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (1, 'OUTCOME', NULL, 'כמה עולים חדשים שולבו בהצלחה בעבודה בסיום תוכנית "עלייה 2000" במהלך חציון א'' 2026?', NULL, '550 עולים', '620 עולים', '772 עולים', '810 עולים', 30, 'QUIZ', NULL, false, NULL, 1, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (1, 'C', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (2, 'OUTCOME', NULL, 'כמה עולים עזבו את מרכזי הקליטה ועברו למגורי קבע בקהילה בחצי השנה הראשונה?', NULL, '450 עולים', '700 עולים', '950 עולים', '1,300 עולים', 30, 'QUIZ', NULL, false, NULL, 2, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (2, 'B', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (3, 'OUTCOME', NULL, 'מה היה אחוז העולים שדיווחו על שביעות רצון גבוהה ומאוד גבוהה מהליך הקליטה בנתב"ג בחציון א''?', NULL, '82.0%', '88.5%', '90.0%', '94.5%', 30, 'QUIZ', NULL, false, NULL, 3, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (3, 'D', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (4, 'OUTCOME', NULL, 'כמה עולים בחרו לקבוע את ביתם ב-5 יישובי המטרה בדרום - קריית גת, אשקלון, שדרות, באר שבע ואילת - בחציון א''?', NULL, '320 עולים', '587 עולים', '740 עולים', '1,100 עולים', 30, 'QUIZ', NULL, false, NULL, 4, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (4, 'B', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (5, 'OUTPUT', 1, 'כמה כיתות "פלא ועל" חדשות לתגבור עברית ולימודים לילדים ונוער נפתחו בעיר תל אביב בחציון א''?', NULL, 'כיתה 1', '2 כיתות', '3 כיתות', '5 כיתות', 20, 'QUIZ', NULL, false, NULL, 5, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (5, 'C', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (6, 'OUTCOME', 1, 'נפתחו 3 כיתות "פלא ועל" חדשות. מהו מדד התוצאה (Outcome) האמיתי שתרצה ההנהלה למדוד בחציון הבא עבור תוכנית זו?', NULL, 'פתיחת 2 כיתות נוספות בחציון ב''', 'עלייה של 30% בציוני העברית והשתלבות נורמטיבית של התלמידים בבתי הספר', 'קיום 15 סדנאות תגבור נוספות במהלך השנה', 'רכישת 50 ספרי לימוד חדשים לכיתות', 30, 'QUIZ', NULL, false, NULL, 6, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (6, 'B', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (7, 'OUTPUT', 2, 'כמה פגישות מ.י.ם (מיפוי, ייעוץ ומעקב) קוימו עם משפחות עולים במרכזי הקליטה במהלך חציון א''?', NULL, '65 פגישות', '85 פגישות', '110 פגישות', '180 פגישות', 20, 'QUIZ', NULL, false, NULL, 7, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (7, 'C', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (8, 'OUTCOME', 2, 'קוימו 110 פגישות מ.י.ם עם משפחות עולים. איזה מהמדדים הבאים מייצג מדד תוצאה (Outcome) של פגישות אלו?', NULL, 'הגדלת מספר הפגישות ל-150 בחציון הבא', 'אחוז העולים שגובשה עבורם תוכנית קליטה אישית שמומשה בהצלחה תוך 6 חודשים', 'הרחבת המערך וביצוע פגישות ל-50 משפחות נוספות', 'הדפסת 200 ערכות מידע לחלוקה בפגישות', 30, 'QUIZ', NULL, false, NULL, 8, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (8, 'B', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (9, 'OUTPUT', 3, 'כמה רופאים השתתפו בקורסי עברית טרום-עלייה שהופעלו בחציון א''?', NULL, '20 רופאים', '40 רופאים', '65 רופאים', '100 רופאים', 20, 'QUIZ', NULL, false, NULL, 9, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (9, 'B', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (10, 'OUTCOME', 3, '40 רופאים משתתפים בקורסי עברית טרום-עלייה. מהו מדד התוצאה (Outcome) שיש למדוד לאחר עלייתם לארץ?', NULL, 'פתיחת 3 קורסי עברית נוספים לרופאים בחו"ל', 'אחוז הרופאים שעברו בהצלחה את בחינת הרישוי והשתלבו במערכת הבריאות תוך שנה', 'הגדלת מכסת המשתתפים בקורסים ל-60 רופאים', 'הגדלת התקציב לקורסי עברית ב-15%', 30, 'QUIZ', NULL, false, NULL, 10, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (10, 'B', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (11, 'OUTPUT', 4, 'כמה עולים הגיעו לישראל בחציון א'' ממדינות שבהן מופעל מערך הליווי לעידוד עלייה?', NULL, '1,200 עולים', '1,650 עולים', '2,005 עולים', '3,100 עולים', 20, 'QUIZ', NULL, false, NULL, 11, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (11, 'C', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (12, 'OUTCOME', 4, '2,005 עולים עלו ממדינות מערך הליווי. איזה מדד יגדיר תוצאה ואימפקט ארוך טווח של פעילות המערך?', NULL, 'הגדלת כמות פגישות ההסברה בחו"ל ב-20%', 'שיעור העולים ממדינות אלו שהשתקעו בישראל ודיווחו על קליטה מוצלחת לאחר 3 שנים', 'ניצול מלא של תקציב הפרסום של מערך הליווי', 'הנפקת 3,000 תעודות זכאות בחו"ל', 30, 'QUIZ', NULL, false, NULL, 12, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (12, 'B', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (13, 'OUTPUT', 5, 'כמה מועמדי עלייה צעירים פנו לקבלת שירות טרום-עלייה בחציון א'' 2026?', NULL, '3,400 פונים', '4,800 פונים', '5,278 פונים', '6,500 פונים', 20, 'QUIZ', NULL, false, NULL, 13, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (13, 'C', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (14, 'OUTCOME', 5, 'רשמנו 5,278 פניות של צעירים בשירות טרום-עלייה. איך נהפוך את הנתון הזה למדד תוצאה (Outcome)?', NULL, 'הגדלת יעד הפניות בחציון ב'' ל-7,000 צעירים', 'אחוז הפונים שפתחו תיק עלייה בפועל והמשיכו לתהליך מימוש תוך 90 יום', 'קיצור זמן ההמתנה למענה טלפוני במוקד ל-2 דקות', 'גיוס 3 נציגי שירות נוספים למוקד', 30, 'QUIZ', NULL, false, NULL, 14, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (14, 'B', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (15, 'OUTPUT', 6, 'בכמה ירידי עלייה ברחבי העולם הופצו מוצרי פרסום והסברה משרדיים בחציון א''?', NULL, '25 ירידים', '38 ירידים', '50 ירידים', '65 ירידים', 20, 'QUIZ', NULL, false, NULL, 15, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (15, 'C', NULL);
INSERT INTO public.questions_public (id, category, pair_id, title, subtitle, answer_a, answer_b, answer_c, answer_d, duration_seconds, scoring_mode, executive_insight, is_placeholder, image_url, order_index, is_enabled) VALUES (16, 'OUTCOME', 6, 'הופצו מוצרי פרסום ב-50 ירידים בעולם. מה מבין הבאים הוא מדד תוצאה (Outcome) המודד את האפקטיביות של המהלך?', NULL, 'הדפסת 10,000 עלוני פרסום נוספים ב-4 שפות', 'גידול של 20% במספר המשתתפים ביריד שנרשמו לייעוץ עלייה אישי בעקבות החשיפה', 'השתתפות ב-60 ירידים בשנה הבאה', 'שמירה על מסגרת התקציב שהוקצתה למוצרי פרסום', 30, 'QUIZ', NULL, false, NULL, 16, true);
INSERT INTO public.question_keys_private (question_id, correct_answer_id, explanation) VALUES (16, 'B', NULL);
SELECT setval('public.questions_public_id_seq', (SELECT max(id) FROM public.questions_public));

CREATE POLICY "question images readable by authenticated"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'question-images');

CREATE POLICY "question images insert by authenticated"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'question-images');

CREATE POLICY "question images update by authenticated"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'question-images')
WITH CHECK (bucket_id = 'question-images');

CREATE POLICY "question images delete by authenticated"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'question-images');